### ISSUE TITLE
Kanban board

### ISSUE THREAD

**Issue by shasherazi** [shasherazi/laptops-ecommerce#24]
We are 5 people in our team
- @shasherazi 
- @monicah79 
- @imranhossainemi 
- @byiringiroscar 
- @fuadmoin 

Here is the link to our [kanban board](https://github.com/users/shasherazi/projects/5/views/1). Below are a few screenshots of our kanban board
![image](https://github.com/shasherazi/laptops-ecommerce/assets/63230301/658b972a-6c94-457d-b30d-88f6aa308dc4)
![image](https://github.com/shasherazi/laptops-ecommerce/assets/63230301/aadbd5de-6171-46a6-bd8d-3dae7076c528)
![image](https://github.com/shasherazi/laptops-ecommerce/assets/63230301/64ac1c63-10e6-4bef-b2eb-7502adae32d7)
![image](https://github.com/shasherazi/laptops-ecommerce/assets/63230301/5caaac04-0313-416f-9c60-d154d0d1f3dc)
![image](https://github.com/shasherazi/laptops-ecommerce/assets/63230301/9168890f-e6c1-4932-b5f9-742296bea7ca)

**Comment by shasherazi** [comment]
Thank you, @Meltrust, for your helpful review. I have added a description to the tasks that need more info

**Comment by Meltrust** [comment]
Hi @shasherazi,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️

- [ ] You added descriptions to some tasks.  We need descriptions for **_all_** tasks.

There are still many tasks without a description:

![image](https://github.com/shasherazi/laptops-ecommerce/assets/57421823/b2573367-1ebd-481b-a799-0a1e497a4751)

Please, add descriptions for all the tasks.  Don't leave any task without a description.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shasherazi** [comment]
Hello @Meltrust, I thought these tasks were pretty self-explanatory from their heading, so I didn't write a description for them. But now I wrote a description for them anyway.
